modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="scable"
version="0.1.0"
displayName="Stackable Cables"
logoFile="logo.png"
authors="iTzhsnu"
description="This Mod Add Stackable Cables and Stackable Tools."

[[dependencies.scable]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

# Here's another dependency
[[dependencies.scable]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
